export const matches = [
  // ROUND 1
  {
    id: 1,
    name: "Round 1 - Match 1",
    nextMatchId: 9,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p1",
        name: "Alice",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "p2",
        name: "Bob",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 2,
    name: "Round 1 - Match 2",
    nextMatchId: 9,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p3",
        name: "Charlie",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "p4",
        name: "Diana",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 3,
    name: "Round 1 - Match 3",
    nextMatchId: 10,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p5",
        name: "Eve",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "p6",
        name: "Frank",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 4,
    name: "Round 1 - Match 4",
    nextMatchId: 10,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p7",
        name: "George",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "p8",
        name: "Hannah",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 5,
    name: "Round 1 - Match 5",
    nextMatchId: 11,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p9",
        name: "Ivan",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "p10",
        name: "Julia",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 6,
    name: "Round 1 - Match 6",
    nextMatchId: 11,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p11",
        name: "Kevin",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "p12",
        name: "Laura",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 7,
    name: "Round 1 - Match 7",
    nextMatchId: 12,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p13",
        name: "Mike",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "p14",
        name: "Nina",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 8,
    name: "Round 1 - Match 8",
    nextMatchId: 12,
    tournamentRoundText: "1",
    startTime: "2025-05-01",
    state: "DONE",
    participants: [
      {
        id: "p15",
        name: "Oscar",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "p16",
        name: "Paula",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },

  // QUARTAS
  {
    id: 9,
    name: "Quarterfinal - Match 9",
    nextMatchId: 13,
    tournamentRoundText: "2",
    startTime: "2025-05-02",
    state: "DONE",
    participants: [
      {
        id: "w1",
        name: "Alice",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "w2",
        name: "Diana",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 10,
    name: "Quarterfinal - Match 10",
    nextMatchId: 13,
    tournamentRoundText: "2",
    startTime: "2025-05-02",
    state: "DONE",
    participants: [
      {
        id: "w3",
        name: "Eve",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "w4",
        name: "Hannah",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 11,
    name: "Quarterfinal - Match 11",
    nextMatchId: 14,
    tournamentRoundText: "2",
    startTime: "2025-05-02",
    state: "DONE",
    participants: [
      {
        id: "w5",
        name: "Ivan",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "w6",
        name: "Laura",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 12,
    name: "Quarterfinal - Match 12",
    nextMatchId: 14,
    tournamentRoundText: "2",
    startTime: "2025-05-02",
    state: "DONE",
    participants: [
      {
        id: "w7",
        name: "Nina",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "w8",
        name: "Oscar",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },

  // SEMIFINAIS
  {
    id: 13,
    name: "Semifinal - Match 13",
    nextMatchId: 15,
    tournamentRoundText: "3",
    startTime: "2025-05-03",
    state: "DONE",
    participants: [
      {
        id: "w9",
        name: "Alice",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
      {
        id: "w10",
        name: "Hannah",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
    ],
  },
  {
    id: 14,
    name: "Semifinal - Match 14",
    nextMatchId: 15,
    tournamentRoundText: "3",
    startTime: "2025-05-03",
    state: "DONE",
    participants: [
      {
        id: "w11",
        name: "Ivan",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "w12",
        name: "Oscar",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },

  // FINAL
  {
    id: 15,
    name: "Final",
    nextMatchId: null,
    tournamentRoundText: "4",
    startTime: "2025-05-04",
    state: "DONE",
    participants: [
      {
        id: "w13",
        name: "Alice",
        isWinner: false,
        resultText: "LOST",
        status: "PLAYED",
      },
      {
        id: "w14",
        name: "Oscar",
        isWinner: true,
        resultText: "WON",
        status: "PLAYED",
      },
    ],
  },
];
